services:
  db:
    image: postgres
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - currencies-backend
  server:
    depends_on:
      - db
    ports:
      - "2000:2000"
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    networks:
      - currencies-backend
networks:
  currencies-backend:
