basePath: /api
definitions:
  rest.BtcUsdtCourseSlice:
    properties:
      timestamp:
        type: integer
      value:
        type: number
    type: object
  rest.BtcUsdtHistoryPage:
    properties:
      history:
        items:
          $ref: '#/definitions/rest.BtcUsdtCourseSlice'
        type: array
      total:
        type: integer
    type: object
  rest.BtcUsdtPaginationRequest:
    properties:
      from_timestamp:
        type: integer
      limit:
        type: integer
      offset:
        type: integer
    type: object
  rest.FiatPaginationRequest:
    properties:
      from_date:
        type: string
      limit:
        type: integer
      offset:
        type: integer
    type: object
  rest.FiatToAnyCourseSlice:
    description: has additional fields consist of currency code and amount, but cant
      image here
    properties:
      base_currency:
        type: string
      date:
        type: string
    type: object
  rest.FiatToAnyHistoryPage:
    properties:
      history:
        items:
          $ref: '#/definitions/rest.FiatToAnyCourseSlice'
        type: array
      total:
        type: integer
    type: object
  rest.UnexpectedResult:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  title: Currencies service api
  version: "1.0"
paths:
  /btcusdt:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.BtcUsdtCourseSlice'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.UnexpectedResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.UnexpectedResult'
      summary: get last BTC USDT course
    post:
      consumes:
      - application/json
      parameters:
      - description: pagination
        in: body
        name: pagination
        required: true
        schema:
          $ref: '#/definitions/rest.BtcUsdtPaginationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.BtcUsdtHistoryPage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.UnexpectedResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.UnexpectedResult'
      summary: get BTC USDT course history with pagination
  /currencies:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.FiatToAnyCourseSlice'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.UnexpectedResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.UnexpectedResult'
      summary: get last fiat to rub course
    post:
      consumes:
      - application/json
      parameters:
      - description: pagination
        in: body
        name: pagination
        required: true
        schema:
          $ref: '#/definitions/rest.FiatPaginationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.FiatToAnyHistoryPage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.UnexpectedResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.UnexpectedResult'
      summary: get fiat to rub course history with pagination
  /latest:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.FiatToAnyCourseSlice'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.UnexpectedResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.UnexpectedResult'
      summary: get last fiat to BTC course
schemes:
- http
swagger: "2.0"
